### ISSUE TITLE
Not working on Mobile devices?

### ISSUE THREAD

**Issue by ChristianOliva** [rishabhp/bideo.js#8]

**Comment by richardatwork** [comment]
Also having the same issue - doesn't autoplay on iOS (iphone 6) and show the play button (but that appears to be disabled / doesn'twork - known issue? This is from stackoverflow: <input type="button" value="Play" onclick="document.myMovie.play()"> ), on iPad, the cover image shows with no play button (which is kind of better), on Windows (Lumia) mobile it works perfectly (_! I know, who'd have though it !_). On Android (Browserstack test) Samsung 6, cover image loads for a second then vanishes, black background remains. Same with Google mobiles. Appreciate any pointers  / workarounds...

**Comment by rishabhp** [comment]
I've updated the code to fix all of this. It might be a bit quirky but try the demo again and let me know how whether its getting any better or not.

**Comment by Zundrium** [comment]
Sadly, with the new code this issue remains on Google mobiles (only one I checked). Could you tell us what you changed in the code?

**Comment by napathello** [comment]
Android have problem get black screen

**Comment by Sakarias-Longhorn** [comment]
Yep, a little google search will tell you that background videos will not autoplay anymore... that's how it is now and I don't think we can fix it without modding our own custom ROM.

**Comment by artbelov** [comment]
As a workaround, you can use "fake" play button with "onclick" event:

```html
<div onclick="document.querySelector('#background_video').play()" class="play-button">
  <i class="fa fa-play-circle" aria-hidden="true"></i>
</div>
```

Temporarily, I hope.

**Comment by nydame** [comment]
By the way, Chrome will not prevent autoplay of videos that are **muted**. Reference: [autoplay policy doc](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).
